# Generated by Django 4.2.5 on 2023-09-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Doner_name", models.CharField(max_length=25)),
                ("Doner_place", models.CharField(max_length=25)),
                ("Doner_address", models.CharField(max_length=50)),
                (
                    "Doner_blood_type",
                    models.CharField(
                        choices=[
                            ("O+ ive", "O POSITIVE"),
                            ("O- ive", "O NEGATIVE"),
                            ("A+ ive", "A POSITIVE"),
                            ("A- ive", "A NEGATIVE"),
                            ("B+ ive", "B POSITIVE"),
                            ("B- ive", "B NEGATIVE"),
                            ("AB+ ive", "AB POSITIVE"),
                            ("AB- ive", "AB NEGATIVE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Doner_contact_number", models.IntegerField()),
            ],
        ),
    ]
