# Generated by Django 4.2.5 on 2023-09-30 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Bapp", "0002_doner_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Buser_name", models.CharField(max_length=25)),
                ("Buser_place", models.CharField(max_length=25)),
                ("Buser_address", models.CharField(max_length=50)),
                (
                    "Buser_blood_type",
                    models.CharField(
                        choices=[
                            ("O+ ive", "O POSITIVE"),
                            ("O- ive", "O NEGATIVE"),
                            ("A+ ive", "A POSITIVE"),
                            ("A- ive", "A NEGATIVE"),
                            ("B+ ive", "B POSITIVE"),
                            ("B- ive", "B NEGATIVE"),
                            ("AB+ ive", "AB POSITIVE"),
                            ("AB- ive", "AB NEGATIVE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Buser_contact_number", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
