# Generated by Django 4.2.5 on 2023-09-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bapp", "0003_buser"),
    ]

    operations = [
        migrations.AddField(
            model_name="buser",
            name="role",
            field=models.CharField(default="Buser", max_length=15),
        ),
        migrations.AddField(
            model_name="doner",
            name="role",
            field=models.CharField(default="Doner", max_length=15),
        ),
    ]
